### ISSUE TITLE
看描述有点意思

### ISSUE THREAD

**Issue by dengshenkk** [pzc105/simplenas#1]
希望来个网站预览或者视频预览

**Comment by pzc105** [comment]
![image](https://github.com/pzc105/simplenas/assets/126746381/1e8d1e86-585d-494b-af97-e2d0e53215f1)
![image](https://github.com/pzc105/simplenas/assets/126746381/f7bc9975-6410-4d97-9b64-e4357f15513e)
![image](https://github.com/pzc105/simplenas/assets/126746381/eacaf5e2-b53b-402c-97b8-f14b6eb1e33d)
![image](https://github.com/pzc105/simplenas/assets/126746381/abd0c666-30af-43e2-86e0-cfd6160483c4)
前端是我边学边做的，所以做的一般了。

**Comment by pzc105** [comment]
https://218.17.0.126:28292/

**Comment by pzc105** [comment]
https://218.17.0.126:28292，https://218.17.0.126:28293
浏览器访问这两个地址，然后信任它们。
第一个是静态网页，第二个是rpc请求的。
ps：出口带宽非常低。
